name: FreeBSD Go Test

on:
  workflow_dispatch:

jobs:
  FreeBSD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cross-platform-actions/action@0.4.2
        with:
          os: freebsd:15.0
          run: |
            cd /usr/local &&
            fetch https://go.dev/dl/go1.26.0.freebsd-amd64.tar.gz &&
            tar -xzf go1.26.0.freebsd-amd64.tar.gz &&
            cd /workspace/Go &&
            /usr/local/go/bin/go mod download &&
            /usr/local/go/bin/go test ./...
            /usr/local/go/bin/go vet ./...
