name: FreeBSD Go Test

on:
  workflow_dispatch:

jobs:
  FreeBSD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cross-platform-actions/action@v0.32.0
        with:
          operating_system: freebsd
          version: '15.0'
          architecture: x86-64
          run: |
            cd /usr/local &&
            fetch --no-verify-peer https://go.dev/dl/go1.26.0.freebsd-amd64.tar.gz &&
            tar -C /usr/local -xzf go1.26.0.linux-amd64.tar.gz
            cd /workspace/Go &&
            /usr/local/go/bin/go mod download &&
            /usr/local/go/bin/go test ./... &&
            /usr/local/go/bin/go vet ./...
