name: FreeBSD Go Test

on:
  workflow_dispatch:

jobs:
  code-check-1.22-github-hosted:
    strategy:
      matrix:
        os:
          - macos-15-intel
          - macos-14
          - macos-15
          - macos-26
          - ubuntu-latest
          - ubuntu-24.04-arm
          - windows-2022
          - windows-2025
          - windows-11-arm
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.22'
      - name: test
        run: go test ./...
      - name: vet
        run: go vet ./...

  code-check-1.22-FreeBSD:
    strategy:
      matrix:
        os:
          - base-os: ubuntu-latest
            cpu-architecture: x86-64
            version: '12.4'
            go-filename: go1.22.12.freebsd-amd64.tar.gz
          - base-os: ubuntu-latest
            cpu-architecture: x86-64
            version: '13.5'
            go-filename: go1.22.12.freebsd-amd64.tar.gz
          - base-os: ubuntu-latest
            cpu-architecture: x86-64
            version: '14.3'
            go-filename: go1.22.12.freebsd-amd64.tar.gz
          - base-os: ubuntu-latest
            cpu-architecture: x86-64
            version: '15.0'
            go-filename: go1.22.12.freebsd-amd64.tar.gz
          - base-os: ubuntu-24.04-arm
            cpu-architecture: arm64
            version: '12.4'
            go-filename: go1.22.12.freebsd-arm64.tar.gz
          - base-os: ubuntu-24.04-arm
            cpu-architecture: arm64
            version: '13.5'
            go-filename: go1.22.12.freebsd-arm64.tar.gz
          - base-os: ubuntu-24.04-arm
            cpu-architecture: arm64
            version: '14.3'
            go-filename: go1.22.12.freebsd-arm64.tar.gz
          - base-os: ubuntu-24.04-arm
            cpu-architecture: arm64
            version: '15.0'
            go-filename: go1.22.12.freebsd-arm64.tar.gz
    runs-on: ${{ matrix.base-os }}
    steps:
      - uses: actions/checkout@v6
      - uses: cross-platform-actions/action@v0.32.0
        with:
          operating_system: freebsd
          version: ${{ matrix.version }}
          architecture: ${{ matrix.cpu-architecture }}
          run: |
            cd /tmp &&
            fetch https://go.dev/dl/${{ matrix.go-filename }} &&
            tar -xzf ${{ matrix.go-filename }} &&
            export PATH=$PATH:/tmp/go/bin &&
            cd ${GITHUB_WORKSPACE}/Go &&
            go mod download &&
            go test ./... &&
            go vet ./...
