name: Code Check darwin/amd64

on:
  workflow_call:
    inputs:
      go_version:
        required: true
        type: string
      os_version:
        required: true
        type: string

jobs:
  darwin-amd64:
    env:
      TARGET: |
        {
          "14": "macos-14-large",
          "15": "macos-15-intel",
          "26": "macos-26-large",
        }
    name: darwin/amd64(macOS ${{ inputs.os_version }})
    runs-on: ${{ fromJson(env.TARGET)[inputs.os_version] }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ inputs.go_version }}
      - run: go vet ./...
      - run: go test ./...
