name: Nest CI 1

on:
  workflow_call:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo nest1 job1
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo nest1 job1
  nest2:
    name: Nest2
    uses: ./.github/workflows/nest-ci-2.yml
