name: Nest CI 2

on:
  workflow_call:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo nest2 job1
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo nest2 job1
  nest3:
    name: Nest3
    uses: ./.github/workflows/nest-ci-3.yml
