name: Node Code Check

on:
  pull_request:
  workflow_dispatch:

env:
  MATRIX_OS: "[\"ubuntu-latest\", \"windows-latest\", \"macos-latest\"]"
  MATRIX_NODE_VERSION: "[18, 20]"

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      os: ${{ steps.matrix.outputs.os }}
      node-version: ${{ steps.matrix.outputs.node-version }}
    steps:
      - name: make values
        id: matrix
        run: |
          echo "os=$(echo '${{ env.MATRIX_OS }}' | jq -c)" >> $GITHUB_OUTPUT
          echo "node-version=$(echo '${{ env.MATRIX_NODE_VERSION }}' | jq -c)" >> $GITHUB_OUTPUT

  job1:
    needs:
      - matrix
    strategy:
      matrix:
        os: ${{ fromJson(needs.matrix.outputs.os) }}
        node-version: ${{ fromJson(needs.matrix.outputs.node-version) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: ${{ matrix.os }} Node.js ${{ matrix.node-version }} Job1
        run: echo ${{ matrix.os }} Node.js ${{ matrix.node-version }} Job1
      - name: outputs
        run: |
          echo "MATRIX_OS: ${{ env.MATRIX_OS }}"
          echo "MATRIX_NODE_VERSION: ${{ env.MATRIX_NODE_VERSION }}"
          echo "os: ${{ matrix.os }}"
          echo "node-version: ${{ matrix.node-version }}"

  job2:
    needs:
      - matrix
      - job1
    strategy:
      matrix:
        os: ${{ fromJson(needs.matrix.outputs.os) }}
        node-version: ${{ fromJson(needs.matrix.outputs.node-version) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: ${{ matrix.os }} Node.js ${{ matrix.node-version }} Job2
        run: echo ${{ matrix.os }} Node.js ${{ matrix.node-version }} Job2
      - name: outputs
        run: |
          echo "MATRIX_OS: ${{ env.MATRIX_OS }}"
          echo "MATRIX_NODE_VERSION: ${{ env.MATRIX_NODE_VERSION }}"
          echo "os: ${{ matrix.os }}"
          echo "node-version: ${{ matrix.node-version }}"

  job3:
    needs:
      - matrix
      - job1
    strategy:
      matrix:
        os: ${{ fromJson(needs.matrix.outputs.os) }}
        node-version: ${{ fromJson(needs.matrix.outputs.node-version) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: ${{ matrix.os }} Node.js ${{ matrix.node-version }} Job3
        run: echo ${{ matrix.os }} Node.js ${{ matrix.node-version }} Job3
      - name: outputs
        run: |
          echo "MATRIX_OS: ${{ env.MATRIX_OS }}"
          echo "MATRIX_NODE_VERSION: ${{ env.MATRIX_NODE_VERSION }}"
          echo "os: ${{ matrix.os }}"
          echo "node-version: ${{ matrix.node-version }}"

  node-code-check-finish:
    if: ${{ always() }}
    needs:
      - job1
      - job2
      - job3
    runs-on: ubuntu-latest
    steps:
      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
